---------------------------------------------------------------------------------
-- Address decode logic for IPbus fabric.
--
-- This file has been AUTOGENERATED from the address table - do not
-- hand edit.
--
-- We assume the synthesis tool is clever enough to recognise
-- exclusive conditions in the if statement.
---------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_address_file_rtMatmul is

-- START automatically generated VHDL (Thu Apr 23 15:36:44 2026)
  constant IPBUS_SEL_WIDTH: positive := 3;
-- END automatically generated VHDL

  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_address_file_rtMatmul(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically generated VHDL (Thu Apr 23 15:36:44 2026)
  constant N_SLV_CSR_CTRL: integer := 0;
  constant N_SLV_CSR_STAT: integer := 1;
  constant N_SLV_INPUT_A_RAM: integer := 2;
  constant N_SLV_INPUT_B_RAM: integer := 3;
  constant N_SLV_OUTPUT_C_RAM: integer := 4;
  constant N_SLAVES: integer := 5;
-- END automatically generated VHDL

end ipbus_decode_address_file_rtMatmul;

package body ipbus_decode_address_file_rtMatmul is

  function ipbus_sel_address_file_rtMatmul(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically generated VHDL (Thu Apr 23 15:36:44 2026)
    if    std_match(addr, "-------------000--------------0-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CSR_CTRL, IPBUS_SEL_WIDTH)); -- csr.ctrl / base 0x00000000 / mask 0x00070002
    elsif std_match(addr, "-------------000--------------1-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CSR_STAT, IPBUS_SEL_WIDTH)); -- csr.stat / base 0x00000002 / mask 0x00070002
    elsif std_match(addr, "-------------001----------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_INPUT_A_RAM, IPBUS_SEL_WIDTH)); -- input_A_RAM / base 0x00010000 / mask 0x00070000
    elsif std_match(addr, "-------------010----------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_INPUT_B_RAM, IPBUS_SEL_WIDTH)); -- input_B_RAM / base 0x00020000 / mask 0x00070000
    elsif std_match(addr, "-------------100----------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_OUTPUT_C_RAM, IPBUS_SEL_WIDTH)); -- output_C_RAM / base 0x00040000 / mask 0x00070000
    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;
-- END automatically generated VHDL

    return sel;

  end function ipbus_sel_address_file_rtMatmul;

end ipbus_decode_address_file_rtMatmul;

---------------------------------------------------------------------------------
